version: '3.9'

services:
  db:
    container_name: taxi-stand-system-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taxi-stand-system-database-01
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./.docker/db/data:/var/lib/mysql  
      - ./.docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./.docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    container_name: taxi-stand-system-app
    build: ./docker/php-swoole
    working_dir: '/var/www/app'
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/app
    depends_on:
      db:
        condition: service_healthy
